version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: dwh_postgres
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: Inda1234
      POSTGRES_DB: data_warehouse
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./scripts/init_schemas.sql:/docker-entrypoint-initdb.d/init_schemas.sql

  minio:
    image: minio/minio
    container_name: dwh_minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

volumes:
  pg_data:
  minio_data:
