csv_sources:
  - source_id: "sale"
    source_type: "csv"
    file_path: "/mnt/d/HG_Project/etl_pipeline/dwh-pipeline-mapping/dwh-pipeline/data/Untitled Discover session.csv"
    sep: ","
    target_staging_table: "staging.sale"
    load_mode: "truncate"
    stream_to_staging: true
  - source_id: "stream_distro"
    source_type: "csv"
    file_path: "/mnt/d/HG_Project/etl_pipeline/dwh-pipeline-mapping/dwh-pipeline/data/fact_view_stream.csv"
    sep: ","
    target_staging_table: "staging.stream_distro"
    load_mode: "truncate"
    stream_to_staging: true
    chunksize: 5000
  - source_id: "usd_rate"
    source_type: "fx"
    start_date: "2025-06-01"
    currency: "vnd"
    target_staging_table: "staging.usd_rate"
    load_mode: "truncate"
    stream_to_staging: true
    batch_days: 30